#EXAMPLE https://registry.terraform.io/providers/hashicorp
resource "local_file" "pet" {
  filename        = "/temp/pets.txt"
  content         = "We love pets!!"
  file_permission = "0700"
  lifecycle {
    create_before_destroy = true
  }
}

resource "local_file" "pet_id" {
  filename = "/temp/pets_id.txt"
  content  = "My pet name is ${random_pet.my-pet.id}"
  depends_on = [
    random_pet.my-pet
  ]
  lifecycle {
    #IT DOES NOT BLOCK THE RESOURCE TO BE DELETE FROM TERRAFORM DESTROY
    prevent_destroy = true
  }
}
output "pet-id-gem" {
  value       = random_pet.my-pet.id
  description = "Record the ID value generated by random_pet"
}
resource "local_file" "pet_map" {
  filename = "/temp/pets_map.txt"
  content  = var.file-content["content3"]
}
resource "local_sensitive_file" "pet-sensitive" {
  filename = "/temp/pets-sensitive.txt"
  content  = "We love dogs!"
}

resource "random_pet" "my-pet" {
  prefix    = "Mrs"
  separator = "."
  length    = "2"
}

resource "local_file" "pet_var" {
  filename = var.filename
  content  = var.content
}

resource "random_pet" "my-var-pet" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.length
}

resource "random_pet" "my-list-pet" {
  prefix    = var.prefix_list[1]
  separator = var.separator
  length    = var.length
}

# resource "random_string" "random_pwd" {
#     count       = "10"
#     length      = "15"
#     min_lower   = "2"
#     min_numeric = "2"
#     min_special = "1"
#     min_upper   = "2"
# }