apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:5.0.17
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_ROOT_PASSWORD
          value: root
        - name: MONGODB_REPLICA_SET_MODE
          value: primary
        - name: MONGODB_REPLICA_SET_KEY
          value: replicasetkey123
        - name: MONGODB_DATABASE
          value: "homebroker"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017