name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Download code base"
      - name: step2
        run: echo "Create the microservices image"
      - name: step3
        run: echo "Push the images to the repository (Docker HUB"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: step1
        run: echo "Download code base"
      - name: step2
        run: echo "Authentication on AWS"
      - name: step3
        run: echo "Microservices deployment on kubernetes"
      
